version: '3.8'

services:
  postgres:
    image: postgres
    container_name: user_controller
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "1357:5432"